# Generated by Django 2.2 on 2022-07-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
